Fix: Remove `var.region`
cloudposse/terraform-aws-mwaa pull request #6
Opened 2022-02-15 21:45 UTC by korenyoni

## what

- Remove `var.region` variable.
- Add `count` meta-attributes to data sources.
- Use `aws_region` data source in place of `var.region`.

## why
- Modules do not usually contain `var.region`, only [components](https://github.com/cloudposse/terraform-aws-components) do. 
- Adding a count meta-attribute to all resources and data sources based on `module.this.enabled` is best-practice as it prevents Terraform from populating the Terraform state needlessly if the module is disabled.

## references
- N/A

2022-02-15 21:46 UTC, korenyoni commented
/test all

2022-02-15 22:01 UTC, korenyoni commented
/test all

2022-02-15 22:09 UTC, korenyoni commented
/test all

2022-02-15 22:50 UTC, korenyoni commented
`test/bats` are failing because `terraform validate .` doesn't take into account that the provider is pinned to `3.x`

https://github.com/cloudposse/terraform-aws-mwaa/blob/4c53a71676c1aba98afd453bb9546113580939c4/test/Makefile#L36-L38

```hcl
± |fix/region-var ?:1 ✗| → terraform validate .
╷
│ Error: Unsupported attribute
│ 
│   on .terraform/modules/mwaa_s3_bucket/main.tf line 166, in resource "aws_s3_bucket" "default":
│  166:         for_each = local.s3_replication_rules == null ? [] : local.s3_replication_rules
│ 
│ This object does not have an attribute named "s3_replication_rules".
```

2022-02-16 00:06 UTC, aknysh commented on main.tf
> +data "aws_partition" "current" {
add empty lines b/w resources

2022-02-16 00:07 UTC, aknysh commented on main.tf
> +  region                 = join("", data.aws_region.current.*.name)
why not use `local.region` is we have it?

2022-02-16 00:08 UTC, Nuru commented
/test all

2022-02-16 12:17 UTC, korenyoni commented
/test all

2022-02-21 22:01 UTC, Nuru requested changes
Leave `var.region` in place. It is a standard required variable for all AWS components and is implied for all AWS modules. The only reason we do not see it more often in modules is that it is usually enough that it is implicitly provided by the AWS provider.

2024-03-02 17:27 UTC, closed without merging